name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-electron.js
    env: 
      TARGET_TOKEN_ELECTROM: ${{ secrets.TARGET_TOKEN_ELECTROM }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-chrome.js
    env: 
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}
  cypress-firefox-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.16.0-chrome105-ff99-edge
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-firefox.js
    env: 
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
      DEBUG: '@cypress/github-action'
